### ISSUE TITLE
How to configure IPs on multiple servers

### ISSUE THREAD

**Issue by goetzk** [mrlesmithjr/ansible-netplan#18]
Hi,
The example says 

```
- hosts: ...your hosts...
...
      netplan_configuration:
...
                - 10.11.12.99/24
```

Its not obvious to me from the role how it decerns which of the hosts (plural) a given IP should apply to.
I'm going to try using host_vars to set it that way but i wonder if thats correct given the example in README.

**Comment by goetzk** [comment]
Update from testing: Seems to use the IP specified in the hosts file; so presumably from the inventory source.

**Comment by maxisam** [comment]
@goetzk Could you share what you meant in code?

Do you mean doing something like


```yml
          ethernets:
            ens160:
              addresses:
                - '{{ansible_host_ip}}/24'
```

**Comment by maxisam** [comment]
never mind,

I figured out

```yml

          ethernets:
            ens160:
              addresses:
                - '{{ansible_default_ipv4.address}}/24'
```
