### ISSUE TITLE
If interface name is set as {{ ansible_default_ipv4.interface }} it just writes the variable name instead of the value

### ISSUE THREAD

**Issue by dimitrihof** [mrlesmithjr/ansible-netplan#39]
**Describe the bug**
Hello i tried your role and have problem with getting the network device name as a variable
```
 netplan_renderer: networkd
 netplan_configuration:
   network:
     version: 2
     ethernets:
        "{{ ansible_default_ipv4.interface }}":
```

These are my first variables, but if i do it like that it doesnt fill in the variable with the network name, instead it just writes the string '{{ ansible_default_ipv4.interface }}' into the config. Is that a Problem with jinja2 templates?

Thanks for your Help!
**To Reproduce**
Use a variable for the default ethernet-if name instead of an actual name.

**Expected behavior**
I expect it to write the default interface name  into the config.
